/* ============ FAMILY BARBERSHOP — shared barber roster ============
   Single source of truth for the team. Loaded before app.js (homepage)
   and styles.js (Haircut Styles page) so both stay in sync. */
window.FB_BARBERS = [
  {
    id: "elvin",
    calendarUrl: "https://api.leadconnectorhq.com/widget/booking/t4RNoRPtemFXfWvGvNg2",
    name: "Elvin Rodriguez",
    specialty: "Skin Fades & Designs",
    years: 21,
    rating: 5.0,
    reviews: 612,
    price: 45,
    status: "open",
    statusText: "Open Today",
    featured: true,
    phone: "(407) 242-3301",
    instagram: "elvin.cuts",
    bio: "Con 21 años de experiencia como barbero profesional, Elvin es uno de los maestros del oficio en Family Barbershop. Su pasión por las líneas perfectas, los fades limpios y el cuidado de cada cliente lo convierten en una pieza fundamental del equipo.",
    tags: ["Skin Fades", "Líneas Precisas", "Diseños"],
    photo: "img/elvin_profile.jpg",
    cuts: [
      "img/elvin_work_1.jpg",
      "img/elvin_work_2.jpg",
      "img/elvin_work_3.jpg",
      "img/elvin_work_4.jpg",
      "img/elvin_work_5.jpg",
      "img/elvin_work_6.jpg",
      "img/elvin_work_7.jpg",
      "img/elvin_work_8.jpg"
    ]
  },
  {
    id: "bebo",
    calendarUrl: "https://api.leadconnectorhq.com/widget/booking/st1sxqMHG53Lu5qAh0mK",
    name: "Bebo",
    specialty: "Precision Cuts & Fades",
    featured: true,
    years: 10,
    rating: 5.0,
    reviews: 120,
    price: 45,
    status: "open",
    statusText: "Open Today",
    phone: "(850) 346-0980",
    instagram: "family.barbershop",
    bio: "Precision cuts, clean fades. Bringing his craft to Family Barbershop.",
    photo: "img/barber2_profile.jpg",
    cuts: [
      "img/barber2_work_1.jpg",
      "img/barber2_work_2.jpg",
      "img/barber2_work_3.jpg",
      "img/barber2_work_1.jpg"
    ]
  },
  {
    id: "peter",
    calendarUrl: "https://api.leadconnectorhq.com/widget/booking/BkxkLoOgz8ajsgvsmClo",
    name: "Peter",
    specialty: "Beard & Style Expert",
    featured: true,
    years: 10,
    rating: 4.9,
    reviews: 356,
    price: 50,
    status: "open",
    statusText: "Open Today",
    phone: "(407) 989-9306",
    instagram: "family.barbershop",
    bio: "Ten years and counting. Peter turns scruff into sculpture — beards, mustaches, and full-face grooming with a straight razor finish.",
    photo: "img/peter_profile.jpg",
    cuts: [
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1500048993953-d23a436266cf?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1562004760-aceed7bb0fe3?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1562157873-818bc0726f68?auto=format&fit=crop&w=400&q=80"
    ]
  },
  {
    id: "kelvo",
    calendarUrl: "https://api.leadconnectorhq.com/widget/booking/2OVzl5S1rmi6DiLh6EKR",
    name: "Kelvo",
    specialty: "Design & Lineup Pro",
    featured: true,
    years: 7,
    rating: 4.9,
    reviews: 198,
    price: 45,
    status: "open",
    statusText: "Open Today",
    phone: "(321) 217-1567",
    instagram: "family.barbershop",
    bio: "If you want a logo, a part, or a freehand design in your fade — Kelvo is the artist. Seven years of clean lines and steady hands.",
    photo: "img/kelvo_profile.jpg",
    cuts: [
      "https://images.unsplash.com/photo-1583195764036-6dc248ac07d9?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1591370874773-6702e8f12fd8?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1605497788044-5a32c7078486?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&w=400&q=80"
    ]
  },
  {
    id: "rafy",
    calendarUrl: "https://api.leadconnectorhq.com/widget/booking/c2N9iE08nlfTg96bn3oG",
    name: "Rafy",
    specialty: "Texture Specialist",
    featured: true,
    years: 9,
    rating: 4.8,
    reviews: 241,
    price: 40,
    status: "busy",
    statusText: "Next 4:45",
    phone: "(407) 319-7849",
    instagram: "dr.cerquillo",
    bio: "Nine years working with every hair type — curls, waves, coarse, fine. Rafy cuts to your texture, not against it.",
    photo: "img/rafy_profile.jpg",
    cuts: [
      "img/rafy_work_1.jpg",
      "img/rafy_work_2.jpg",
      "img/rafy_work_3.jpg",
      "img/rafy_work_4.jpg",
      "img/rafy_work_5.jpg",
      "img/rafy_work_6.jpg",
      "img/rafy_work_7.jpg",
      "img/rafy_work_8.jpg"
    ]
  },
  {
    id: "jose",
    calendarUrl: "https://api.leadconnectorhq.com/widget/booking/RoNKxA9hOBPZKUrrBGa7",
    name: "Jose",
    specialty: "Classic Cuts Expert",
    featured: true,
    years: 15,
    rating: 5.0,
    reviews: 520,
    price: 50,
    status: "open",
    statusText: "Open Today",
    phone: "(786) 234-6663",
    instagram: "jr_dahalloffamer",
    bio: "Fifteen years in the trade. Jose handles the classics — pompadours, side parts, scissor cuts — like the old-school masters who taught him.",
    photo: "img/jose_profile.jpg",
    cuts: [
      "https://images.unsplash.com/photo-1542327897-d73f4005b533?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1622287162716-f311baa1a2b8?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1509695507497-903c140c43b0?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&w=400&q=80"
    ]
  },
  {
    id: "yamil",
    calendarUrl: "https://api.leadconnectorhq.com/widget/booking/LgjCdxwJFgV6O0Ruo24w",
    name: "Yamil",
    specialty: "Curly & Natural Hair",
    featured: true,
    years: 8,
    rating: 4.9,
    reviews: 267,
    price: 45,
    status: "open",
    statusText: "Open Today",
    phone: "(407) 432-9548",
    instagram: "family.barbershop",
    bio: "Eight years specializing in curly and natural textures. Yamil cuts dry, shapes the curl pattern, and finishes with a sponge twist if you want it.",
    photo: "img/yamil_profile.jpg",
    cuts: [
      "https://images.unsplash.com/photo-1615109398623-88346a601842?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1605497788044-5a32c7078486?auto=format&fit=crop&w=400&q=80"
    ]
  }
];
